addpath([pwd, '/flow'], ...
        [pwd, '/utilities'], ...
        [pwd, '/flow/speed'], ...
        [pwd, '/flow/pattern'], ...
        [pwd, '/flow/entropy'], ...
        [pwd, '/image'],...
        [pwd, '/image/entropy']);